Text_BootUpPC:
	.string "{PLAYER} communed with the Blade of Evil's\n"
	.string "Bane.$"

gText_WhichPCShouldBeAccessed::
	.string "Which power shall be invoked?$"

gText_AccessedSomeonesPC::
	.string "Accessed SOMEONE'S VAULT.$"

gText_StorageSystemOpened::
	.string "POKéMON Storage System opened.$"

gText_AccessedPlayersPC::
	.string "Accessed {PLAYER}'s SATCHEL.$"

gText_AccessedLanettesPC::
	.string "Accessed FI's VAULT.$"
